service:
  name: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "2"

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules:
      forceExclude:
        - aws-sdk

functions:
  getProductsList:
    handler: src/lambdas/getProductsList.get
    events:
      - http:
          method: get
          path: products
          cors: true
  getProductsById:
    handler: src/lambdas/getProductsById.get
    events:
      - http:
          method: get
          path: products/{productId}
          cors: true
  createProduct:
    handler: src/lambdas/createProduct.add
    events:
      - http:
          method: post
          path: products
          cors: true
